export const LOAD_ALL_COMMITS_REQUEST = 'LOAD_ALL_COMMITS_REQUEST';
export const LOAD_ALL_COMMITS_SUCCESSFULLY = 'LOAD_ALL_COMMITS_SUCCESSFULLY';
export const LOAD_ALL_COMMITS_FAILURE = 'LOAD_ALL_COMMITS_FAILURE';

export const LOAD_COMMIT_BY_ID_REQUEST = 'LOAD_COMMIT_BY_ID_REQUEST';
export const LOAD_COMMIT_BY_ID_SUCCESSFULLY = 'LOAD_COMMIT_BY_ID_SUCCESSFULLY';
export const LOAD_COMMIT_BY_ID_FAILURE = 'LOAD_COMMIT_BY_ID_FAILURE';